import type { NextPageContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { trpc } from '../utils/trpc'
import { useForm } from 'react-hook-form'
import { articleCollection, db, Article } from 'models/client'
import { aql } from 'arangojs'
import debug from 'debug'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/router'

// --- Ory Interaction ---
import { Configuration, V0alpha2Api, Session, Identity } from '@ory/client'
import { edgeConfig } from '@ory/integrations/next'

const ory = new V0alpha2Api(new Configuration(edgeConfig))
const getUserName = (identity: Identity) => identity.traits.email || identity.traits.username

const log = debug('pages/index')

const SaveArticleInput = () => {
  const mutation = trpc.useMutation(['article.parse'])
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm()

  const onSubmit = (data: any) => mutation.mutate({ url: data.url })

  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <input
        type='text'
        placeholder='https://'
        className='input input-ghost w-full max-w-xs'
        {...register('url', { required: true, maxLength: 80 })}
      />

      <button type='submit' className='btn btn-ghost'>
        submit
      </button>
    </form>
  )
}

export default function Home({ articles }: { articles: Article[] }) {
  const router = useRouter()
  const [session, setSession] = useState<Session | undefined>()
  useEffect(() => {
    ory
      .toSession()
      .then(({ data }) => {
        // User has a session!
        setSession(data)
      })
      .catch(() => {
        // Redirect to login page
        return router.push(edgeConfig.basePath + '/ui/login')
      })
  }, [router])

  if (!session) {
    // Still loading
    return null
  }

  return (
    <>
      <Head>
        <title>Reink</title>
        <meta
          name='description'
          content='Generated by create next app and using NextUI as a react UI library'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container mx-auto px-2'>
        <h1 className='normal-case text-4xl text-center py-4 font-black'>ᚱᛖᛁᚾᚲ</h1>

        <div className='border-2 border-x-0 border-black py-1'>
          <div className='border border-x-0 border-black py-2'>
            You have {articles.length} articles / {getUserName(session.identity)}
          </div>
        </div>

        <SaveArticleInput />

        <div className='pt-4 font-serif'>
          {articles &&
            articles.map((doc) => {
              return (
                <div key={doc._key} className='mb-4'>
                  <h2 className='card-title font-serif'>{doc.title}</h2>
                  <p>
                    {doc.description}
                    <Link href={`/article/${doc._key}`}>
                      <a className='link ml-2'>Read more...</a>
                    </Link>
                  </p>
                </div>
              )
            })}
        </div>

        <div className='columns-2 p-2 font-serif text-justify'></div>
      </div>
    </>
  )
}

export async function getServerSideProps(ctx: NextPageContext) {
  try {
    const r = await db.query(aql`
      for doc in ${articleCollection}
        LIMIT 10
        return doc
    `)

    const articles = await r.all()

    return {
      props: {
        articles,
      },
    }
  } catch (e) {
    console.error(e)
    return { props: { id: ctx.query.id as string, doc: null } }
  }
}
