import { trpc } from 'utils/trpc'
import { COOKIE_NAME_INSTAPAPER_TOKEN } from 'utils/auth'
import { hasCookie } from 'cookies-next'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const App = () => {
  const result = trpc.useQuery(['instapaper.list'])

  return (
    <>
      <Head>
        <title>Reink</title>
        <meta
          name='description'
          content='Generated by create next app and using NextUI as a react UI library'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <div className='container mx-auto px-2'>
        <h1 className='normal-case text-4xl text-center py-4 font-black'>ᚱᛖᛁᚾᚲ</h1>

        <div className='pt-4 font-serif'>
          {result.data &&
            result.data.map((doc) => {
              if (doc.type !== 'bookmark') {
                return null
              }

              return (
                <div key={doc.hash} className='mb-4'>
                  <h2 className='card-title font-serif'>{doc.title}</h2>
                  <p>
                    {doc.description}
                    <Link className='link ml-2' href={`/article/instapaper-${doc.bookmark_id}`}>
                      Read more...
                    </Link>
                  </p>
                </div>
              )
            })}
        </div>

        <div className='columns-2 p-2 font-serif text-justify'></div>
      </div>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const hasInstapaperCookie = hasCookie(COOKIE_NAME_INSTAPAPER_TOKEN, { req, res })

  if (!hasInstapaperCookie) {
    return { props: {}, redirect: { destination: '/auth/connect' } }
  }

  return { props: {} }
}

export default App
